import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'es' | 'it' | 'de' | 'pt';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Traductions par défaut (seront étendues)
export const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.discovery': 'Découverte',
    'nav.artists': 'Artistes',
    'nav.events': 'Événements',
    'nav.dashboard': 'Tableau de bord',
    'nav.forum': 'Forum',
    'nav.messages': 'Messages',
    'nav.musicStore': 'Boutique Musique',
    'nav.musicHub': 'Music Hub',
    'nav.subscription': 'Abonnement',
    'nav.logout': 'Déconnexion',
    'nav.createAccount': 'Créer un compte',
    
    // General
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.book': 'Réserver',
    'common.contact': 'Contacter',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.download': 'Télécharger',
    'common.upload': 'Téléverser',
    'common.bookings': 'réservations',
    
    // DJ Map
    'map.title': 'Carte des DJs',
    'map.searchCity': 'Rechercher une ville...',
    'map.allStyles': 'Tous les styles',
    'map.allAvailability': 'Toute disponibilité',
    'map.availableNow': 'Disponible maintenant',
    'map.thisWeekend': 'Ce week-end',
    
    // DJ Profile
    'profile.about': 'À propos',
    'profile.music': 'Musique',
    'profile.events': 'Événements',
    'profile.booking': 'Réservation',
    'profile.presskit': 'Press Kit',
    'profile.bio': 'Biographie',
    'profile.genres': 'Genres musicaux',
    'profile.location': 'Localisation',
    'profile.experience': 'Expérience',
    
    // Press Kit
    'presskit.title': 'Press Kit',
    'presskit.upload': 'Glisser-déposer vos fichiers ici ou cliquer pour sélectionner',
    'presskit.supported': 'Formats supportés: PDF, JPG, PNG, MP3, MP4',
    'presskit.documents': 'Documents',
    'presskit.no_documents': 'Aucun document disponible',
    
    // Booking
    'booking.title': 'Réserver cet artiste',
    'booking.date': 'Date de l\'événement',
    'booking.time': 'Heure',
    'booking.duration': 'Durée',
    'booking.venue': 'Lieu',
    'booking.budget': 'Budget',
    'booking.message': 'Message',
    'booking.submit': 'Envoyer la demande',
    
    // Language selector
    'language.select': 'Choisir la langue',
    'language.french': 'Français',
    'language.english': 'Anglais',
    'language.spanish': 'Espagnol',
    'language.italian': 'Italien',
    'language.german': 'Allemand',
    'language.portuguese': 'Portugais',

    // Social features
    'social.like': 'J\'aime',
    'social.likes': 'J\'aime',
    'social.follow': 'Suivre',
    'social.following': 'Suivi',
    'social.followers': 'Abonnés',
    'social.reviews': 'Avis',
    'social.addReview': 'Laisser un avis',
    'social.rating': 'Note',
    'social.comment': 'Commentaire',
    'social.publish': 'Publier',
    'social.noReviews': 'Aucun avis pour le moment',
    'social.firstReview': 'Soyez le premier à laisser un avis !',

    // Community
    'community.title': 'Communauté',
    'community.playlist': 'Mixtape du Mois',
    'community.propose': 'Proposer un morceau',
    'community.vote': 'Voter',
    'community.listen': 'Écouter',
    'community.download': 'Télécharger',
    'community.official': 'Playlist Officielle',
    'community.pending': 'Propositions en cours',
    'community.selected': 'morceaux sélectionnés',
    'community.propositions': 'propositions',
    'community.trackTitle': 'Titre du morceau',
    'community.artist': 'Artiste',
    'community.genre': 'Genre',
    'community.proposedBy': 'Proposé par',
    'community.onePerMonth': 'Chaque utilisateur peut proposer un morceau par mois',

    // Genres musicaux
    'genres.house': 'House',
    'genres.techno': 'Techno',
    'genres.kizomba': 'Kizomba',
    'genres.salsa': 'Salsa',
    'genres.bachata': 'Bachata',
    'genres.afro': 'Afro',
    'genres.electro': 'Electro',
    'genres.deephouse': 'Deep House',
    'genres.progressive': 'Progressive',
    'genres.hiphop': 'Hip-Hop',
    'genres.rnb': 'R&B',
    'genres.edm': 'EDM',
    'genres.trance': 'Trance',
    'genres.ambient': 'Ambient',
    'genres.drumandbass': 'Drum & Bass',
    'genres.dubstep': 'Dubstep',
    'genres.funk': 'Funk',
    'genres.disco': 'Disco',
    'genres.latin': 'Latin',
    'genres.reggaeton': 'Reggaeton',
    'genres.dancehall': 'Dancehall',
    'genres.trap': 'Trap',
    'genres.rock': 'Rock',
    'genres.electronic': 'Electronic',
    'genres.reggae': 'Reggae',

    // Textes divers
    'misc.artists': 'Artistes',
    'misc.found': 'trouvé',
    'misc.foundPlural': 'trouvés',
    'misc.artist': 'artiste',
    'misc.artistPlural': 'artistes',
    'misc.noArtistsFound': 'Aucun artiste trouvé',
    'misc.modifySearch': 'Essayez de modifier vos critères de recherche',
    'misc.clearFilters': 'Effacer les filtres',
    'misc.musicStore': 'Boutique Musique',
    'misc.community': 'Communauté',
    'misc.events': 'Événements',
    'misc.geolocation': 'Géolocalisation',
    'misc.locationError': 'Erreur de localisation',
    'misc.locating': 'Localisation...',
    'misc.positionFound': 'Position trouvée',
    'misc.distance': 'Distance max',
    'misc.km': 'km',
    'misc.available': 'Disponible',
    'misc.busy': 'Occupé',
    'misc.viewProfile': 'Voir le profil',
    'misc.book': 'Booker',
    'misc.cancel': 'Annuler',
    'misc.save': 'Enregistrer',
    'misc.edit': 'Modifier',
    'misc.delete': 'Supprimer',
    'misc.upload': 'Téléverser',
    'misc.download': 'Télécharger',
    'misc.listen': 'Écouter',
    'misc.vote': 'Voter',
    'misc.publish': 'Publier',
    'misc.proposedBy': 'Proposé par',
    'misc.trackTitle': 'Titre du morceau',
    'misc.artistName': 'Nom de l\'artiste',
    'misc.genreOptional': 'Genre (optionnel)',
    'misc.comment': 'Commentaire',
    'misc.rating': 'Note',
    'misc.shareExperience': 'Partagez votre expérience avec ce DJ...',
    'misc.firstReview': 'Soyez le premier à laisser un avis !',
    'misc.noReviews': 'Aucun avis pour le moment',
    'misc.leaveReview': 'Laisser un avis',
    'misc.reviews': 'Avis',
    'misc.follow': 'Suivre',
    'misc.following': 'Suivi',
    'misc.unfollow': 'Ne plus suivre',
    'misc.followers': 'Abonnés',
    'misc.bookings': 'réservations',
    'misc.upcomingEvents': 'Prochains événements',
    'misc.musicPricing': 'Prix par Musique',
    'misc.configuredMusic': 'Musiques Configurées',
    'misc.premiumCommunity': 'Bienvenue dans la communauté premium DJHUB !',
    'misc.loginRequired': 'Veuillez vous connecter pour acheter de la musique',
    'misc.artistReceives': 'Artiste reçoit:',
    'misc.supportArtists': 'Chaque achat soutient directement les artistes avec seulement 2% de commission.',
    'misc.searchTrackArtist': 'Rechercher une track ou un artiste...',
    'misc.modifyFilters': 'Essayez de modifier vos filtres de recherche.',
    'misc.forArtists': 'Pour les artistes:',
    'misc.joinCommunity': 'Rejoignez la communauté DJHUB',
    'misc.connectTalentedDJs': 'Connectez-vous avec des DJs talentueux, écoutez leur musique et réservez-les pour votre prochain événement',
    'misc.popularEvents': 'Événements populaires',
    'misc.createAccount': 'Créez votre compte pour réserver des DJs, gérer vos événements et découvrir de nouveaux talents',
    'misc.searchDJs': 'Rechercher des DJs...',
    'misc.manageProfile': 'Gérez votre profil, musique et réservations',
    'misc.uploadMusic': 'Uploader de la musique',
    'misc.bookingCalendar': 'Calendrier des réservations',
    'misc.djSection': 'Cette section est réservée aux DJs pour gérer leurs prix de musique.',
    'misc.describeStyle': 'Décrivez votre style et expérience...',
    'misc.minBookingHours': 'Réservation minimum (heures)',
    'misc.accessToMusic': 'L\'accès à la musique',
    'misc.accessToPressKit': 'L\'accès au Press Kit',
    'misc.cancelSubscription': 'Annuler l\'abonnement',
    'misc.mobileOptimized': 'Cette application est optimisée pour mobile uniquement. Veuillez utiliser votre téléphone pour une meilleure expérience.',
    
    // Discovery page
    'discovery.exploreMap': 'Explorer la carte',
    'discovery.joinFindMyDJ': 'Rejoignez FindMyDJ',
    'discovery.signUpFree': 'S\'inscrire gratuitement',
    'discovery.alreadyAccount': 'Déjà un compte ?',
    'discovery.signIn': 'Se connecter',
    
    // Forum
    'forum.title': 'Forum Communautaire',
    'forum.subtitle': 'Partagez vos questions, astuces et expériences avec la communauté DJ',
    'forum.createPost': 'Nouveau post',
    'forum.searchForum': 'Rechercher dans le forum...',
    'forum.backToForum': 'Retour au forum',
    'forum.all': 'Tous',
    'forum.questions': 'Questions',
    'forum.tips': 'Astuces',
    'forum.discussions': 'Discussions',
    'forum.equipment': 'Équipement',
    'forum.gigs': 'Gigs',
    'forum.music': 'Musique',
    'forum.events': 'Événements',
    'forum.newest': 'Plus récents',
    'forum.popular': 'Plus populaires',
    'forum.mostReplies': 'Plus de réponses',
    'forum.noPostsFound': 'Aucun post trouvé',
    'forum.startDiscussion': 'Commencez une nouvelle discussion !',
    'forum.timeAgo.lessThanHour': 'Il y a moins d\'une heure',
    'forum.timeAgo.hours': 'Il y a {hours}h',
    'forum.timeAgo.days': 'Il y a {days}j',
    
    // Messages
    'messages.title': 'Messages',
    'messages.noPermission': 'Vous n\'avez pas la permission de répondre aux messages',
    'messages.searchConversations': 'Rechercher une conversation...',
    'messages.noConversations': 'Aucune conversation encore',
    'messages.startMessaging': 'Commencez à échanger avec d\'autres DJs et organisateurs d\'événements !',
    'messages.typeMessage': 'Tapez votre message...',
    'messages.selectConversation': 'Sélectionnez une conversation',
    'messages.chooseConversation': 'Choisissez une conversation dans la liste pour commencer à discuter',
    'messages.online': 'En ligne',
    'messages.offline': 'Hors ligne',
    'messages.client': 'Client',

    // Formulaires et placeholders
    'forms.yourName': 'Votre nom',
    'forms.fanMelomane': 'Fan / Mélomane',
    'forms.ruleName': 'Nom de la règle',
    'forms.price': 'Prix',
    'forms.newPlaylist': 'Ma nouvelle playlist',
    'forms.addTag': 'Ajouter un tag',

    // Notifications et messages système
    'notifications.infoCopied': 'Informations copiées dans le presse-papiers !',
    'notifications.linkCopied': 'Lien copié dans le presse-papiers !',
    'notifications.subscriptionCancelled': 'Abonnement annulé avec succès ! (Simulation)',
    'notifications.subscriptionActivated': 'Abonnement {planName} activé avec succès ! (Simulation)',
    'notifications.pricesSaved': 'Prix sauvegardés avec succès !',
    'notifications.paymentError': 'Erreur lors du processus de paiement. Veuillez réessayer.',
    'notifications.cancellationError': 'Erreur lors de l\'annulation. Veuillez réessayer.',
    'notifications.planChangeError': 'Erreur lors du changement de plan. Veuillez réessayer.',
    'notifications.loginRequired': 'Veuillez vous connecter pour acheter de la musique',
    'notifications.trackAlreadyOwned': 'Vous possédez déjà cette track',
    'notifications.purchaseError': 'Erreur lors de l\'achat. Veuillez réessayer.',
    'notifications.downloadStarted': 'Téléchargement en cours...',
    'notifications.bookingRequestSent': 'Demande de réservation envoyée ! Le DJ vous contactera bientôt.',

    // Filtres et tri
    'filters.newest': 'Plus récents',
    'filters.priority': 'Priorité',
    'filters.bestRated': 'Mieux notés',
    'filters.automatic': 'Automatique',
    'filters.highQuality': 'Haute (320 kbps)',
    'filters.relaxation': 'Relaxation',
    'filters.sport': 'Sport',
    'filters.allPrices': 'Tous les prix',
    'filters.under2euros': 'Moins de 2€',

    // Gestion des prix
    'pricing.title': 'Gestion des Prix',
    'pricing.saveAll': 'Sauvegarder Tout',
    'pricing.priceRules': 'Règles de Prix',
    'pricing.newRule': 'Nouvelle Règle',
    'pricing.ruleName': 'Nom de la règle',
    'pricing.price': 'Prix',
    'pricing.add': 'Ajouter',
    'pricing.cancel': 'Annuler',
    'pricing.descriptionOptional': 'Description (optionnel)',
    'pricing.musicPricing': 'Prix par Musique',
    'pricing.currentPrice': 'Prix actuel',
    'pricing.customPrice': 'Prix personnalisé',
    'pricing.customPricePlaceholder': 'Prix custom',
    'pricing.averagePrice': 'Prix Moyen',
    'pricing.estimatedRevenue': 'Revenus Estimés',
    'pricing.afterCommission': 'Après commission 2%',
    'pricing.configuredMusic': 'Musiques Configurées',
    'pricing.singleStandard': 'Single Standard',
    'pricing.remixPremium': 'Remix Premium',
    'pricing.singleStandardDesc': 'Prix standard pour un single',
    'pricing.remixPremiumDesc': 'Prix pour les remixes exclusifs',
    'pricing.single': 'Single',
    'pricing.album': 'Album',
    'pricing.remix': 'Remix',
    'pricing.exclusive': 'Exclusif',

    // Playlists
    'playlist.title': 'Mes Playlists',
    'playlist.create': 'Créer',
    'playlist.createPlaylist': 'Créer une playlist',
    'playlist.playlistName': 'Nom de la playlist',
    'playlist.playlistNamePlaceholder': 'Ma nouvelle playlist',
    'playlist.description': 'Description',
    'playlist.descriptionPlaceholder': 'Description de votre playlist...',
    'playlist.tags': 'Tags',
    'playlist.addTag': 'Ajouter un tag',
    'playlist.addTagPlaceholder': 'Ajouter un tag',
    'playlist.publicPlaylist': 'Playlist publique',
    'playlist.collaborativePlaylist': 'Playlist collaborative',
    'playlist.searchPlaylists': 'Rechercher des playlists...',
    'playlist.all': 'Toutes',
    'playlist.personal': 'Personnelles',
    'playlist.shared': 'Partagées',
    'playlist.public': 'Publiques',
    'playlist.favorites': 'Favoris',
    'playlist.recentlyModified': 'Récemment modifiées',
    'playlist.recentlyCreated': 'Récemment créées',
    'playlist.name': 'Nom',
    'playlist.duration': 'Durée',
    'playlist.trackCount': 'Nombre de pistes',
    'playlist.tracks': 'pistes',
    'playlist.noPlaylistsFound': 'Aucune playlist trouvée',
    'playlist.noPlaylists': 'Aucune playlist',
    'playlist.modifySearch': 'Essayez de modifier votre recherche',
    'playlist.createFirst': 'Créez votre première playlist pour commencer',
    'playlist.createFirstButton': 'Créer ma première playlist',
  },
  en: {
    // Navigation
    'nav.discovery': 'Discovery',
    'nav.artists': 'Artists',
    'nav.events': 'Events',
    'nav.dashboard': 'Dashboard',
    'nav.forum': 'Forum',
    'nav.messages': 'Messages',
    'nav.musicStore': 'Music Store',
    'nav.musicHub': 'Music Hub',
    'nav.subscription': 'Subscription',
    'nav.logout': 'Logout',
    'nav.createAccount': 'Create Account',
    
    // General
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.book': 'Book',
    'common.contact': 'Contact',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.bookings': 'bookings',
    
    // DJ Map
    'map.title': 'DJ Map',
    'map.searchCity': 'Search for a city...',
    'map.allStyles': 'All styles',
    'map.allAvailability': 'All availability',
    'map.availableNow': 'Available now',
    'map.thisWeekend': 'This weekend',
    
    // DJ Profile
    'profile.about': 'About',
    'profile.music': 'Music',
    'profile.events': 'Events',
    'profile.booking': 'Booking',
    'profile.presskit': 'Press Kit',
    'profile.bio': 'Biography',
    'profile.genres': 'Musical Genres',
    'profile.location': 'Location',
    'profile.experience': 'Experience',
    
    // Press Kit
    'presskit.title': 'Press Kit',
    'presskit.upload': 'Drag and drop your files here or click to select',
    'presskit.supported': 'Supported formats: PDF, JPG, PNG, MP3, MP4',
    'presskit.documents': 'Documents',
    'presskit.no_documents': 'No documents available',
    
    // Booking
    'booking.title': 'Book this artist',
    'booking.date': 'Event date',
    'booking.time': 'Time',
    'booking.duration': 'Duration',
    'booking.venue': 'Venue',
    'booking.budget': 'Budget',
    'booking.message': 'Message',
    'booking.submit': 'Send request',
    
    // Language selector
    'language.select': 'Select language',
    'language.french': 'French',
    'language.english': 'English',
    'language.spanish': 'Spanish',
    'language.italian': 'Italian',
    'language.german': 'German',
    'language.portuguese': 'Portuguese',

    // Social features
    'social.like': 'Like',
    'social.likes': 'Likes',
    'social.follow': 'Follow',
    'social.following': 'Following',
    'social.followers': 'Followers',
    'social.reviews': 'Reviews',
    'social.addReview': 'Leave a review',
    'social.rating': 'Rating',
    'social.comment': 'Comment',
    'social.publish': 'Publish',
    'social.noReviews': 'No reviews yet',
    'social.firstReview': 'Be the first to leave a review!',

    // Community
    'community.title': 'Community',
    'community.playlist': 'Monthly Mixtape',
    'community.propose': 'Propose a track',
    'community.vote': 'Vote',
    'community.listen': 'Listen',
    'community.download': 'Download',
    'community.official': 'Official Playlist',
    'community.pending': 'Pending proposals',
    'community.selected': 'selected tracks',
    'community.propositions': 'proposals',
    'community.trackTitle': 'Track title',
    'community.artist': 'Artist',
    'community.genre': 'Genre',
    'community.proposedBy': 'Proposed by',
    'community.onePerMonth': 'Each user can propose one track per month',

    // Musical genres
    'genres.house': 'House',
    'genres.techno': 'Techno',
    'genres.kizomba': 'Kizomba',
    'genres.salsa': 'Salsa',
    'genres.bachata': 'Bachata',
    'genres.afro': 'Afro',
    'genres.electro': 'Electro',
    'genres.deephouse': 'Deep House',
    'genres.progressive': 'Progressive',
    'genres.hiphop': 'Hip-Hop',
    'genres.rnb': 'R&B',
    'genres.edm': 'EDM',
    'genres.trance': 'Trance',
    'genres.ambient': 'Ambient',
    'genres.drumandbass': 'Drum & Bass',
    'genres.dubstep': 'Dubstep',
    'genres.funk': 'Funk',
    'genres.disco': 'Disco',
    'genres.latin': 'Latin',
    'genres.reggaeton': 'Reggaeton',
    'genres.dancehall': 'Dancehall',
    'genres.trap': 'Trap',
    'genres.rock': 'Rock',
    'genres.electronic': 'Electronic',
    'genres.reggae': 'Reggae',

    // Miscellaneous texts
    'misc.artists': 'Artists',
    'misc.found': 'found',
    'misc.foundPlural': 'found',
    'misc.artist': 'artist',
    'misc.artistPlural': 'artists',
    'misc.noArtistsFound': 'No artists found',
    'misc.modifySearch': 'Try modifying your search criteria',
    'misc.clearFilters': 'Clear filters',
    'misc.musicStore': 'Music Store',
    'misc.community': 'Community',
    'misc.events': 'Events',
    'misc.geolocation': 'Geolocation',
    'misc.locationError': 'Location error',
    'misc.locating': 'Locating...',
    'misc.positionFound': 'Position found',
    'misc.distance': 'Max distance',
    'misc.km': 'km',
    'misc.available': 'Available',
    'misc.busy': 'Busy',
    'misc.viewProfile': 'View profile',
    'misc.book': 'Book',
    'misc.cancel': 'Cancel',
    'misc.save': 'Save',
    'misc.edit': 'Edit',
    'misc.delete': 'Delete',
    'misc.upload': 'Upload',
    'misc.download': 'Download',
    'misc.listen': 'Listen',
    'misc.vote': 'Vote',
    'misc.publish': 'Publish',
    'misc.proposedBy': 'Proposed by',
    'misc.trackTitle': 'Track title',
    'misc.artistName': 'Artist name',
    'misc.genreOptional': 'Genre (optional)',
    'misc.comment': 'Comment',
    'misc.rating': 'Rating',
    'misc.shareExperience': 'Share your experience with this DJ...',
    'misc.firstReview': 'Be the first to leave a review!',
    'misc.noReviews': 'No reviews yet',
    'misc.leaveReview': 'Leave a review',
    'misc.reviews': 'Reviews',
    'misc.follow': 'Follow',
    'misc.following': 'Following',
    'misc.unfollow': 'Unfollow',
    'misc.followers': 'Followers',
    'misc.bookings': 'bookings',
    'misc.upcomingEvents': 'Upcoming events',
    'misc.musicPricing': 'Music Pricing',
    'misc.configuredMusic': 'Configured Music',
    'misc.premiumCommunity': 'Welcome to the DJHUB premium community!',
    'misc.loginRequired': 'Please log in to purchase music',
    'misc.artistReceives': 'Artist receives:',
    'misc.supportArtists': 'Each purchase directly supports artists with only 2% commission.',
    'misc.searchTrackArtist': 'Search for a track or artist...',
    'misc.modifyFilters': 'Try modifying your search filters.',
    'misc.forArtists': 'For artists:',
    'misc.joinCommunity': 'Join the DJHUB community',
    'misc.connectTalentedDJs': 'Connect with talented DJs, listen to their music and book them for your next event',
    'misc.popularEvents': 'Popular events',
    'misc.createAccount': 'Create your account to book DJs, manage your events and discover new talents',
    'misc.searchDJs': 'Search for DJs...',
    'misc.manageProfile': 'Manage your profile, music and bookings',
    'misc.uploadMusic': 'Upload music',
    'misc.bookingCalendar': 'Booking calendar',
    'misc.djSection': 'This section is reserved for DJs to manage their music pricing.',
    'misc.describeStyle': 'Describe your style and experience...',
    'misc.minBookingHours': 'Minimum booking (hours)',
    'misc.accessToMusic': 'Access to music',
    'misc.accessToPressKit': 'Access to Press Kit',
    'misc.cancelSubscription': 'Cancel subscription',
    'misc.mobileOptimized': 'This app is optimized for mobile only. Please use your phone for a better experience.',
    
    // Discovery page
    'discovery.exploreMap': 'Explore the map',
    'discovery.joinFindMyDJ': 'Join FindMyDJ',
    'discovery.signUpFree': 'Sign up for free',
    'discovery.alreadyAccount': 'Already have an account?',
    'discovery.signIn': 'Sign in',
    
    // Forum
    'forum.title': 'Community Forum',
    'forum.subtitle': 'Share your questions, tips and experiences with the DJ community',
    'forum.createPost': 'New post',
    'forum.searchForum': 'Search in forum...',
    'forum.backToForum': 'Back to forum',
    'forum.all': 'All',
    'forum.questions': 'Questions',
    'forum.tips': 'Tips',
    'forum.discussions': 'Discussions',
    'forum.equipment': 'Equipment',
    'forum.gigs': 'Gigs',
    'forum.music': 'Music',
    'forum.events': 'Events',
    'forum.newest': 'Newest',
    'forum.popular': 'Most popular',
    'forum.mostReplies': 'Most replies',
    'forum.noPostsFound': 'No posts found',
    'forum.startDiscussion': 'Start a new discussion!',
    'forum.timeAgo.lessThanHour': 'Less than an hour ago',
    'forum.timeAgo.hours': '{hours}h ago',
    'forum.timeAgo.days': '{days}d ago',
    
    // Messages
    'messages.title': 'Messages',
    'messages.noPermission': 'You do not have permission to reply to messages',
    'messages.searchConversations': 'Search conversations...',
    'messages.noConversations': 'No conversations yet',
    'messages.startMessaging': 'Start messaging with other DJs and event organizers!',
    'messages.typeMessage': 'Type a message...',
    'messages.selectConversation': 'Select a conversation',
    'messages.chooseConversation': 'Choose a conversation from the list to start chatting',
    'messages.online': 'Online',
    'messages.offline': 'Offline',
    'messages.client': 'Client',

    // Forms and placeholders
    'forms.yourName': 'Your name',
    'forms.fanMelomane': 'Fan / Music Lover',
    'forms.ruleName': 'Rule name',
    'forms.price': 'Price',
    'forms.newPlaylist': 'My new playlist',
    'forms.addTag': 'Add tag',

    // Notifications and system messages
    'notifications.infoCopied': 'Information copied to clipboard!',
    'notifications.linkCopied': 'Link copied to clipboard!',
    'notifications.subscriptionCancelled': 'Subscription cancelled successfully! (Simulation)',
    'notifications.pricesSaved': 'Prices saved successfully!',
    'notifications.paymentError': 'Error during payment process. Please try again.',
    'notifications.cancellationError': 'Error during cancellation. Please try again.',
    'notifications.planChangeError': 'Error during plan change. Please try again.',
    'notifications.loginRequired': 'Please log in to purchase music',
    'notifications.alreadyOwned': 'You already own this track',
    'notifications.purchaseError': 'Error during purchase. Please try again.',
    'notifications.downloadStarted': 'Download in progress...',
    'notifications.bookingRequestSent': 'Booking request sent! The DJ will contact you soon.',

    // Filters and sorting
    'filters.newest': 'Newest',
    'filters.priority': 'Priority',
    'filters.bestRated': 'Best rated',
    'filters.automatic': 'Automatic',
    'filters.highQuality': 'High (320 kbps)',
    'filters.relaxation': 'Relaxation',
    'filters.sport': 'Sport',
    'filters.allPrices': 'All prices',
    'filters.under2euros': 'Under 2€',

    // Pricing management
    'pricing.title': 'Price Management',
    'pricing.saveAll': 'Save All',
    'pricing.priceRules': 'Price Rules',
    'pricing.newRule': 'New Rule',
    'pricing.ruleName': 'Rule name',
    'pricing.price': 'Price',
    'pricing.add': 'Add',
    'pricing.cancel': 'Cancel',
    'pricing.descriptionOptional': 'Description (optional)',
    'pricing.musicPricing': 'Music Pricing',
    'pricing.currentPrice': 'Current price',
    'pricing.customPrice': 'Custom price',
    'pricing.customPricePlaceholder': 'Custom price',
    'pricing.averagePrice': 'Average Price',
    'pricing.estimatedRevenue': 'Estimated Revenue',
    'pricing.afterCommission': 'After 2% commission',
    'pricing.configuredMusic': 'Configured Music',
    'pricing.singleStandard': 'Standard Single',
    'pricing.remixPremium': 'Premium Remix',
    'pricing.singleStandardDesc': 'Standard price for a single',
    'pricing.remixPremiumDesc': 'Price for exclusive remixes',
    'pricing.single': 'Single',
    'pricing.album': 'Album',
    'pricing.remix': 'Remix',
    'pricing.exclusive': 'Exclusive',

    // Playlists
    'playlist.title': 'My Playlists',
    'playlist.create': 'Create',
    'playlist.createPlaylist': 'Create a playlist',
    'playlist.playlistName': 'Playlist name',
    'playlist.playlistNamePlaceholder': 'My new playlist',
    'playlist.description': 'Description',
    'playlist.descriptionPlaceholder': 'Description of your playlist...',
    'playlist.tags': 'Tags',
    'playlist.addTag': 'Add tag',
    'playlist.addTagPlaceholder': 'Add tag',
    'playlist.publicPlaylist': 'Public playlist',
    'playlist.collaborativePlaylist': 'Collaborative playlist',
    'playlist.searchPlaylists': 'Search playlists...',
    'playlist.all': 'All',
    'playlist.personal': 'Personal',
    'playlist.shared': 'Shared',
    'playlist.public': 'Public',
    'playlist.favorites': 'Favorites',
    'playlist.recentlyModified': 'Recently modified',
    'playlist.recentlyCreated': 'Recently created',
    'playlist.name': 'Name',
    'playlist.duration': 'Duration',
    'playlist.trackCount': 'Number of tracks',
    'playlist.tracks': 'tracks',
    'playlist.noPlaylistsFound': 'No playlists found',
    'playlist.noPlaylists': 'No playlists',
    'playlist.modifySearch': 'Try modifying your search',
    'playlist.createFirst': 'Create your first playlist to get started',
    'playlist.createFirstButton': 'Create my first playlist',
  },
  es: {
   // Navigation
    'nav.discovery': 'Descubrimiento',
    'nav.artists': 'Artistas',
    'nav.events': 'Eventos',
    'nav.dashboard': 'Panel de control',
     'nav.forum': 'Foro',
     'nav.messages': 'Mensajes',
     'nav.musicStore': 'Tienda de Música',
     'nav.musicHub': 'Centro Musical',
    'nav.subscription': 'Suscripción',
    'nav.logout': 'Cerrar Sesión',
    'nav.createAccount': 'Crear Cuenta',
    
    // General
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.book': 'Reservar',
    'common.contact': 'Contactar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.download': 'Descargar',
    'common.upload': 'Subir',
    'common.bookings': 'reservas',
    
    // DJ Map
    'map.title': 'Mapa de DJs',
    'map.searchCity': 'Buscar una ciudad...',
    'map.allStyles': 'Todos los estilos',
    'map.allAvailability': 'Toda disponibilidad',
    'map.availableNow': 'Disponible ahora',
    'map.thisWeekend': 'Este fin de semana',
    
    // DJ Profile
    'profile.about': 'Acerca de',
    'profile.music': 'Música',
    'profile.events': 'Eventos',
    'profile.booking': 'Reserva',
    'profile.presskit': 'Kit de Prensa',
    'profile.bio': 'Biografía',
    'profile.genres': 'Géneros Musicales',
    'profile.location': 'Ubicación',
    'profile.experience': 'Experiencia',
    
    // Press Kit
    'presskit.title': 'Kit de Prensa',
    'presskit.upload': 'Arrastra y suelta tus archivos aquí o haz clic para seleccionar',
    'presskit.supported': 'Formatos soportados: PDF, JPG, PNG, MP3, MP4',
    'presskit.documents': 'Documentos',
    'presskit.no_documents': 'No hay documentos disponibles',
    
    // Booking
    'booking.title': 'Reservar este artista',
    'booking.date': 'Fecha del evento',
    'booking.time': 'Hora',
    'booking.duration': 'Duración',
    'booking.venue': 'Lugar',
    'booking.budget': 'Presupuesto',
    'booking.message': 'Mensaje',
    'booking.submit': 'Enviar solicitud',
    
    // Language selector
    'language.select': 'Seleccionar idioma',
    'language.french': 'Francés',
    'language.english': 'Inglés',
    'language.spanish': 'Español',
    'language.italian': 'Italiano',
    'language.german': 'Alemán',
    'language.portuguese': 'Portugués',

    // Social features
    'social.like': 'Me gusta',
    'social.likes': 'Me gusta',
    'social.follow': 'Seguir',
    'social.following': 'Siguiendo',
    'social.followers': 'Seguidores',
    'social.reviews': 'Reseñas',
    'social.addReview': 'Dejar una reseña',
    'social.rating': 'Calificación',
    'social.comment': 'Comentario',
    'social.publish': 'Publicar',
    'social.noReviews': 'Aún no hay reseñas',
    'social.firstReview': '¡Sé el primero en dejar una reseña!',

    // Community
    'community.title': 'Comunidad',
    'community.playlist': 'Mixtape Mensual',
    'community.propose': 'Proponer una pista',
    'community.vote': 'Votar',
    'community.listen': 'Escuchar',
    'community.download': 'Descargar',
    'community.official': 'Lista de Reproducción Oficial',
    'community.pending': 'Propuestas pendientes',
    'community.selected': 'pistas seleccionadas',
    'community.propositions': 'propuestas',
    'community.trackTitle': 'Título de la pista',
    'community.artist': 'Artista',
    'community.genre': 'Género',
    'community.proposedBy': 'Propuesto por',
    'community.onePerMonth': 'Cada usuario puede proponer una pista por mes',

    // Musical genres
    'genres.house': 'House',
    'genres.techno': 'Techno',
    'genres.kizomba': 'Kizomba',
    'genres.salsa': 'Salsa',
    'genres.bachata': 'Bachata',
    'genres.afro': 'Afro',
    'genres.electro': 'Electro',
    'genres.deephouse': 'Deep House',
    'genres.progressive': 'Progresivo',
    'genres.hiphop': 'Hip-Hop',
    'genres.rnb': 'R&B',
    'genres.edm': 'EDM',
    'genres.trance': 'Trance',
    'genres.ambient': 'Ambient',
    'genres.drumandbass': 'Drum & Bass',
    'genres.dubstep': 'Dubstep',
    'genres.funk': 'Funk',
    'genres.disco': 'Disco',
    'genres.latin': 'Latino',
    'genres.reggaeton': 'Reggaeton',
    'genres.dancehall': 'Dancehall',
    'genres.trap': 'Trap',
    'genres.rock': 'Rock',
    'genres.electronic': 'Electrónico',
    'genres.reggae': 'Reggae',

    // Miscellaneous texts
    'misc.artists': 'Artistas',
    'misc.found': 'encontrado',
    'misc.foundPlural': 'encontrados',
    'misc.artist': 'artista',
    'misc.artistPlural': 'artistas',
    'misc.noArtistsFound': 'No se encontraron artistas',
    'misc.modifySearch': 'Intenta modificar tus criterios de búsqueda',
    'misc.clearFilters': 'Limpiar filtros',
    'misc.musicStore': 'Tienda de Música',
    'misc.community': 'Comunidad',
    'misc.events': 'Eventos',
    'misc.geolocation': 'Geolocalización',
    'misc.locationError': 'Error de ubicación',
    'misc.locating': 'Localizando...',
    'misc.positionFound': 'Posición encontrada',
    'misc.distance': 'Distancia máxima',
    'misc.km': 'km',
    'misc.available': 'Disponible',
    'misc.busy': 'Ocupado',
    'misc.viewProfile': 'Ver perfil',
    'misc.book': 'Reservar',
    'misc.cancel': 'Cancelar',
    'misc.save': 'Guardar',
    'misc.edit': 'Editar',
    'misc.delete': 'Eliminar',
    'misc.upload': 'Subir',
    'misc.download': 'Descargar',
    'misc.listen': 'Escuchar',
    'misc.vote': 'Votar',
    'misc.publish': 'Publicar',
    'misc.proposedBy': 'Propuesto por',
    'misc.trackTitle': 'Título de la pista',
    'misc.artistName': 'Nombre del artista',
    'misc.genreOptional': 'Género (opcional)',
    'misc.comment': 'Comentario',
    'misc.rating': 'Calificación',
    'misc.shareExperience': 'Comparte tu experiencia con este DJ...',
    'misc.firstReview': '¡Sé el primero en dejar una reseña!',
    'misc.noReviews': 'Aún no hay reseñas',
    'misc.leaveReview': 'Dejar una reseña',
    'misc.reviews': 'Reseñas',
    'misc.follow': 'Seguir',
    'misc.following': 'Siguiendo',
    'misc.unfollow': 'Dejar de seguir',
    'misc.followers': 'Seguidores',
    'misc.bookings': 'reservas',
    'misc.upcomingEvents': 'Próximos eventos',
    'misc.musicPricing': 'Precios de Música',
    'misc.configuredMusic': 'Música Configurada',
    'misc.premiumCommunity': '¡Bienvenido a la comunidad premium de DJHUB!',
    'misc.loginRequired': 'Por favor inicia sesión para comprar música',
    'misc.artistReceives': 'El artista recibe:',
    'misc.supportArtists': 'Cada compra apoya directamente a los artistas con solo 2% de comisión.',
    'misc.searchTrackArtist': 'Buscar una pista o artista...',
    'misc.modifyFilters': 'Intenta modificar tus filtros de búsqueda.',
    'misc.forArtists': 'Para artistas:',
    'misc.joinCommunity': 'Únete a la comunidad DJHUB',
    'misc.connectTalentedDJs': 'Conecta con DJs talentosos, escucha su música y contrátalos para tu próximo evento',
    'misc.popularEvents': 'Eventos populares',
    'misc.createAccount': 'Crea tu cuenta para reservar DJs, gestionar tus eventos y descubrir nuevos talentos',
    'misc.searchDJs': 'Buscar DJs...',
    'misc.manageProfile': 'Gestiona tu perfil, música y reservas',
    'misc.uploadMusic': 'Subir música',
    'misc.bookingCalendar': 'Calendario de reservas',
    'misc.djSection': 'Esta sección está reservada para que los DJs gestionen sus precios de música.',
    'misc.describeStyle': 'Describe tu estilo y experiencia...',
    'misc.minBookingHours': 'Reserva mínima (horas)',
    'misc.accessToMusic': 'Acceso a música',
    'misc.accessToPressKit': 'Acceso al Press Kit',
    'misc.cancelSubscription': 'Cancelar suscripción',
    'misc.mobileOptimized': 'Esta aplicación está optimizada solo para móviles. Por favor usa tu teléfono para una mejor experiencia.',
    
    // Discovery page
    'discovery.exploreMap': 'Explorar el mapa',
    'discovery.joinFindMyDJ': 'Únete a FindMyDJ',
    'discovery.signUpFree': 'Regístrate gratis',
    'discovery.alreadyAccount': '¿Ya tienes una cuenta?',
    'discovery.signIn': 'Iniciar sesión',
    
    // Forum
    'forum.title': 'Foro de la Comunidad',
    'forum.subtitle': 'Comparte tus preguntas, consejos y experiencias con la comunidad DJ',
    'forum.createPost': 'Nueva publicación',
    'forum.searchForum': 'Buscar en el foro...',
    'forum.backToForum': 'Volver al foro',
    'forum.all': 'Todos',
    'forum.questions': 'Preguntas',
    'forum.tips': 'Consejos',
    'forum.discussions': 'Discusiones',
    'forum.equipment': 'Equipo',
    'forum.gigs': 'Conciertos',
    'forum.music': 'Música',
    'forum.events': 'Eventos',
    'forum.newest': 'Más recientes',
    'forum.popular': 'Más populares',
    'forum.mostReplies': 'Más respuestas',
    'forum.noPostsFound': 'No se encontraron publicaciones',
    'forum.startDiscussion': '¡Inicia una nueva discusión!',
    'forum.timeAgo.lessThanHour': 'Hace menos de una hora',
    'forum.timeAgo.hours': 'Hace {hours}h',
    'forum.timeAgo.days': 'Hace {days}d',
    
    // Messages
    'messages.title': 'Mensajes',
    'messages.noPermission': 'No tienes permiso para responder a mensajes',
    'messages.searchConversations': 'Buscar conversaciones...',
    'messages.noConversations': 'Aún no hay conversaciones',
    'messages.startMessaging': '¡Comienza a enviar mensajes con otros DJs y organizadores de eventos!',
    'messages.typeMessage': 'Escribe un mensaje...',
    'messages.selectConversation': 'Seleccionar una conversación',
    'messages.chooseConversation': 'Elige una conversación de la lista para empezar a chatear',
    'messages.online': 'En línea',
    'messages.offline': 'Desconectado',
    'messages.client': 'Cliente',

    // Formularios y marcadores de posición
    'forms.yourName': 'Tu nombre',
    'forms.fanMelomane': 'Fan / Melómano',
    'forms.ruleName': 'Nombre de la regla',
    'forms.price': 'Precio',
    'forms.newPlaylist': 'Mi nueva lista de reproducción',
    'forms.addTag': 'Añadir etiqueta',

    // Notificaciones y mensajes del sistema
    'notifications.infoCopied': '¡Información copiada al portapapeles!',
    'notifications.linkCopied': '¡Enlace copiado al portapapeles!',
    'notifications.subscriptionCancelled': '¡Suscripción cancelada con éxito! (Simulación)',
    'notifications.pricesSaved': '¡Precios guardados con éxito!',
    'notifications.paymentError': 'Error durante el proceso de pago. Por favor, inténtalo de nuevo.',
    'notifications.cancellationError': 'Error durante la cancelación. Por favor, inténtalo de nuevo.',
    'notifications.planChangeError': 'Error durante el cambio de plan. Por favor, inténtalo de nuevo.',
    'notifications.loginRequired': 'Por favor, inicia sesión para comprar música',
    'notifications.trackAlreadyOwned': 'Ya posees esta pista',
    'notifications.purchaseError': 'Error durante la compra. Por favor, inténtalo de nuevo.',
    'notifications.downloadStarted': 'Descarga en progreso...',
    'notifications.bookingRequestSent': '¡Solicitud de reserva enviada! El DJ te contactará pronto.',

    // Filtros y ordenación
    'filters.newest': 'Más recientes',
    'filters.priority': 'Prioridad',
    'filters.bestRated': 'Mejor valorados',
    'filters.automatic': 'Automático',
    'filters.highQuality': 'Alta (320 kbps)',
    'filters.relaxation': 'Relajación',
    'filters.sport': 'Deporte',
    'filters.allPrices': 'Todos los precios',
    'filters.under2euros': 'Menos de 2€',

    // Gestión de precios
    'pricing.title': 'Gestión de Precios',
    'pricing.saveAll': 'Guardar Todo',
    'pricing.priceRules': 'Reglas de Precio',
    'pricing.newRule': 'Nueva Regla',
    'pricing.ruleName': 'Nombre de la regla',
    'pricing.price': 'Precio',
    'pricing.add': 'Añadir',
    'pricing.cancel': 'Cancelar',
    'pricing.descriptionOptional': 'Descripción (opcional)',
    'pricing.musicPricing': 'Precio por Música',
    'pricing.currentPrice': 'Precio actual',
    'pricing.customPrice': 'Precio personalizado',
    'pricing.customPricePlaceholder': 'Precio personalizado',
    'pricing.averagePrice': 'Precio Promedio',
    'pricing.estimatedRevenue': 'Ingresos Estimados',
    'pricing.afterCommission': 'Después de comisión 2%',
    'pricing.configuredMusic': 'Música Configurada',
    'pricing.singleStandard': 'Single Estándar',
    'pricing.remixPremium': 'Remix Premium',
    'pricing.singleStandardDesc': 'Precio estándar para un single',
    'pricing.remixPremiumDesc': 'Precio para remixes exclusivos',
    'pricing.single': 'Single',
    'pricing.album': 'Álbum',
    'pricing.remix': 'Remix',
    'pricing.exclusive': 'Exclusivo',

    // Playlist
    'playlist.title': 'Filtrar y ordenar las playlists',
    'playlist.create': 'Crear',
    'playlist.createPlaylist': 'Crear una playlist',
    'playlist.playlistName': 'Nombre de la playlist *',
    'playlist.playlistNamePlaceholder': 'Nombre de la playlist',
    'playlist.description': 'Descripción',
    'playlist.descriptionPlaceholder': 'Descripción de la playlist',
    'playlist.tags': 'Tags',
    'playlist.addTag': 'Agregar tag',
    'playlist.addTagPlaceholder': 'Agregar un tag',
    'playlist.publicPlaylist': 'Playlist pública',
    'playlist.collaborativePlaylist': 'Playlist colaborativa',
    'playlist.searchPlaylists': 'Buscar playlists...',
    'playlist.all': 'Todas',
    'playlist.personal': 'Personales',
    'playlist.shared': 'Compartidas',
    'playlist.public': 'Públicas',
    'playlist.favorites': 'Favoritos',
    'playlist.recentlyModified': 'Recientemente modificadas',
    'playlist.recentlyCreated': 'Recientemente creadas',
    'playlist.name': 'Nombre',
    'playlist.duration': 'Duración',
    'playlist.trackCount': 'Número de pistas',
    'playlist.tracks': 'pistas',
    'playlist.noPlaylistsFound': 'Ninguna playlist encontrada',
    'playlist.noPlaylists': 'Ninguna playlist',
    'playlist.modifySearch': 'Intenta modificar tu búsqueda',
    'playlist.createFirst': 'Crea tu primera playlist para comenzar',
    'playlist.createFirstButton': 'Crear mi primera playlist'
  },
  it: {
    // Navigation
    'nav.discovery': 'Scoperta',
    'nav.artists': 'Artisti',
    'nav.events': 'Eventi',
    'nav.dashboard': 'Dashboard',
    'nav.forum': 'Forum',
    'nav.messages': 'Messaggi',
    'nav.musicStore': 'Negozio Musicale',
    'nav.musicHub': 'Music Hub',
    'nav.subscription': 'Abbonamento',
    'nav.logout': 'Disconnetti',
    'nav.createAccount': 'Crea Account',
    
    // General
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.book': 'Prenota',
    'common.contact': 'Contatta',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.edit': 'Modifica',
    'common.delete': 'Elimina',
    'common.download': 'Scarica',
    'common.upload': 'Carica',
    'common.bookings': 'prenotazioni',
    
    // DJ Map
    'map.title': 'Mappa DJ',
    'map.searchCity': 'Cerca una città...',
    'map.allStyles': 'Tutti gli stili',
    'map.allAvailability': 'Tutta la disponibilità',
    'map.availableNow': 'Disponibile ora',
    'map.thisWeekend': 'Questo weekend',
    
    // DJ Profile
    'profile.about': 'Chi sono',
    'profile.music': 'Musica',
    'profile.events': 'Eventi',
    'profile.booking': 'Prenotazione',
    'profile.presskit': 'Kit Stampa',
    'profile.bio': 'Biografia',
    'profile.genres': 'Generi Musicali',
    'profile.location': 'Posizione',
    'profile.experience': 'Esperienza',
    
    // Press Kit
    'presskit.title': 'Kit Stampa',
    'presskit.upload': 'Trascina e rilascia i tuoi file qui o clicca per selezionare',
    'presskit.supported': 'Formati supportati: PDF, JPG, PNG, MP3, MP4',
    'presskit.documents': 'Documenti',
    'presskit.no_documents': 'Nessun documento disponibile',
    
    // Booking
    'booking.title': 'Prenota questo artista',
    'booking.date': 'Data evento',
    'booking.time': 'Ora',
    'booking.duration': 'Durata',
    'booking.venue': 'Luogo',
    'booking.budget': 'Budget',
    'booking.message': 'Messaggio',
    'booking.submit': 'Invia richiesta',
    
    // Language selector
    'language.select': 'Seleziona lingua',
    'language.french': 'Francese',
    'language.english': 'Inglese',
    'language.spanish': 'Spagnolo',
    'language.italian': 'Italiano',
    'language.german': 'Tedesco',
    'language.portuguese': 'Portoghese',
    
    // Discovery page
    'discovery.exploreMap': 'Esplora la mappa',
    'discovery.joinFindMyDJ': 'Unisciti a FindMyDJ',
    'discovery.signUpFree': 'Registrati gratuitamente',
    'discovery.alreadyAccount': 'Hai già un account?',
    'discovery.signIn': 'Accedi',
    
    // Forum
    'forum.title': 'Forum della Comunità',
    'forum.subtitle': 'Condividi le tue domande, consigli ed esperienze con la comunità DJ',
    'forum.createPost': 'Nuovo post',
    'forum.searchForum': 'Cerca nel forum...',
    'forum.backToForum': 'Torna al forum',
    'forum.all': 'Tutti',
    'forum.questions': 'Domande',
    'forum.tips': 'Consigli',
    'forum.discussions': 'Discussioni',
    'forum.equipment': 'Attrezzatura',
    'forum.gigs': 'Concerti',
    'forum.music': 'Musica',
    'forum.events': 'Eventi',
    'forum.newest': 'Più recenti',
    'forum.popular': 'Più popolari',
    'forum.mostReplies': 'Più risposte',
    'forum.noPostsFound': 'Nessun post trovato',
    'forum.startDiscussion': 'Inizia una nuova discussione!',
    'forum.timeAgo.lessThanHour': 'Meno di un\'ora fa',
    'forum.timeAgo.hours': '{hours}h fa',
    'forum.timeAgo.days': '{days}g fa',
    
    // Messages
    'messages.title': 'Messaggi',
    'messages.noPermission': 'Non hai il permesso di rispondere ai messaggi',
    'messages.searchConversations': 'Cerca conversazioni...',
    'messages.noConversations': 'Nessuna conversazione ancora',
    'messages.startMessaging': 'Inizia a messaggiare con altri DJ e organizzatori di eventi!',
    'messages.typeMessage': 'Scrivi un messaggio...',
    'messages.selectConversation': 'Seleziona una conversazione',
    'messages.chooseConversation': 'Scegli una conversazione dalla lista per iniziare a chattare',
    'messages.online': 'Online',
    'messages.offline': 'Offline',
    'messages.client': 'Cliente',

    // Moduli e segnaposto
    'forms.yourName': 'Il tuo nome',
    'forms.fanMelomane': 'Fan / Melomane',
    'forms.ruleName': 'Nome della regola',
    'forms.price': 'Prezzo',
    'forms.newPlaylist': 'La mia nuova playlist',
    'forms.addTag': 'Aggiungi tag',

    // Notifiche e messaggi di sistema
    'notifications.infoCopied': 'Informazioni copiate negli appunti!',
    'notifications.linkCopied': 'Link copiato negli appunti!',
    'notifications.subscriptionCancelled': 'Abbonamento cancellato con successo! (Simulazione)',
    'notifications.pricesSaved': 'Prezzi salvati con successo!',
    'notifications.paymentError': 'Errore durante il processo di pagamento. Riprova.',
    'notifications.cancellationError': 'Errore durante la cancellazione. Riprova.',
    'notifications.planChangeError': 'Errore durante il cambio di piano. Riprova.',
    'notifications.loginRequired': 'Accedi per acquistare musica',
    'notifications.alreadyOwned': 'Possiedi già questa traccia',
    'notifications.purchaseError': 'Errore durante l\'acquisto. Riprova.',
    'notifications.downloadStarted': 'Download in corso...',
    'notifications.bookingRequestSent': 'Richiesta di prenotazione inviata! Il DJ ti contatterà presto.',

    // Prezzi
    'pricing.title': 'Gestione Prezzi',
    'pricing.saveAll': 'Salva Tutto',
    'pricing.priceRules': 'Regole di Prezzo',
    'pricing.newRule': 'Nuova Regola',
    'pricing.ruleName': 'Nome della regola',
    'pricing.price': 'Prezzo',
    'pricing.add': 'Aggiungi',
    'pricing.cancel': 'Annulla',
    'pricing.descriptionOptional': 'Descrizione (opzionale)',
    'pricing.musicPricing': 'Prezzi per Musica',
    'pricing.currentPrice': 'Prezzo attuale',
    'pricing.customPrice': 'Prezzo personalizzato',
    'pricing.customPricePlaceholder': 'Prezzo personalizzato',
    'pricing.averagePrice': 'Prezzo Medio',
    'pricing.estimatedRevenue': 'Ricavi Stimati',
    'pricing.afterCommission': 'Dopo commissione 2%',
    'pricing.configuredMusic': 'Musiche Configurate',
    'pricing.singleStandard': 'Single Standard',
    'pricing.remixPremium': 'Remix Premium',
    'pricing.singleStandardDesc': 'Prezzo standard per un singolo',
    'pricing.remixPremiumDesc': 'Prezzo per remix esclusivi',
    'pricing.single': 'Singolo',
    'pricing.album': 'Album',
    'pricing.remix': 'Remix',
    'pricing.exclusive': 'Esclusivo',

    // Playlist
    'playlist.title': 'Filtra e ordina le playlist',
    'playlist.create': 'Crea',
    'playlist.createPlaylist': 'Crea una playlist',
    'playlist.playlistName': 'Nome della playlist *',
    'playlist.playlistNamePlaceholder': 'Nome della playlist',
    'playlist.description': 'Descrizione',
    'playlist.descriptionPlaceholder': 'Descrizione della playlist',
    'playlist.tags': 'Tag',
    'playlist.addTag': 'Aggiungi tag',
    'playlist.addTagPlaceholder': 'Aggiungi un tag',
    'playlist.publicPlaylist': 'Playlist pubblica',
    'playlist.collaborativePlaylist': 'Playlist collaborativa',
    'playlist.searchPlaylists': 'Cerca playlist...',
    'playlist.all': 'Tutte',
    'playlist.personal': 'Personali',
    'playlist.shared': 'Condivise',
    'playlist.public': 'Pubbliche',
    'playlist.favorites': 'Preferiti',
    'playlist.recentlyModified': 'Modificate di recente',
    'playlist.recentlyCreated': 'Create di recente',
    'playlist.name': 'Nome',
    'playlist.duration': 'Durata',
    'playlist.trackCount': 'Numero di tracce',
    'playlist.tracks': 'tracce',
    'playlist.noPlaylistsFound': 'Nessuna playlist trovata',
    'playlist.noPlaylists': 'Nessuna playlist',
    'playlist.modifySearch': 'Prova a modificare la tua ricerca',
    'playlist.createFirst': 'Crea la tua prima playlist per iniziare',
    'playlist.createFirstButton': 'Crea la mia prima playlist',

    // Filtri e ordinamento
    'filters.newest': 'Più recenti',
    'filters.priority': 'Priorità',
    'filters.bestRated': 'Meglio valutati',
    'filters.automatic': 'Automatico',
    'filters.highQuality': 'Alta (320 kbps)',
    'filters.relaxation': 'Relax',
    'filters.sport': 'Sport',
    'filters.allPrices': 'Tutti i prezzi',
    'filters.under2euros': 'Sotto 2€'
  },
  de: {
    // Navigation
    'nav.discovery': 'Entdeckung',
    'nav.artists': 'Künstler',
    'nav.events': 'Veranstaltungen',
    'nav.dashboard': 'Dashboard',
    'nav.forum': 'Forum',
    'nav.messages': 'Nachrichten',
    'nav.musicStore': 'Musikgeschäft',
    'nav.musicHub': 'Music Hub',
    'nav.subscription': 'Abonnement',
    'nav.logout': 'Abmelden',
    'nav.createAccount': 'Konto Erstellen',
    
    // General
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.book': 'Buchen',
    'common.contact': 'Kontakt',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.edit': 'Bearbeiten',
    'common.delete': 'Löschen',
    'common.download': 'Herunterladen',
    'common.upload': 'Hochladen',
    'common.bookings': 'Buchungen',
    
    // DJ Map
    'map.title': 'DJ-Karte',
    'map.searchCity': 'Nach einer Stadt suchen...',
    'map.allStyles': 'Alle Stile',
    'map.allAvailability': 'Alle Verfügbarkeiten',
    'map.availableNow': 'Jetzt verfügbar',
    'map.thisWeekend': 'Dieses Wochenende',
    
    // DJ Profile
    'profile.about': 'Über mich',
    'profile.music': 'Musik',
    'profile.events': 'Veranstaltungen',
    'profile.booking': 'Buchung',
    'profile.presskit': 'Pressekit',
    'profile.bio': 'Biografie',
    'profile.genres': 'Musikrichtungen',
    'profile.location': 'Standort',
    'profile.experience': 'Erfahrung',
    
    // Press Kit
    'presskit.title': 'Pressekit',
    'presskit.upload': 'Dateien hier hineinziehen oder klicken zum Auswählen',
    'presskit.supported': 'Unterstützte Formate: PDF, JPG, PNG, MP3, MP4',
    'presskit.documents': 'Dokumente',
    'presskit.no_documents': 'Keine Dokumente verfügbar',
    
    // Booking
    'booking.title': 'Diesen Künstler buchen',
    'booking.date': 'Veranstaltungsdatum',
    'booking.time': 'Uhrzeit',
    'booking.duration': 'Dauer',
    'booking.venue': 'Veranstaltungsort',
    'booking.budget': 'Budget',
    'booking.message': 'Nachricht',
    'booking.submit': 'Anfrage senden',
    
    // Language selector
    'language.select': 'Sprache wählen',
    'language.french': 'Französisch',
    'language.english': 'Englisch',
    'language.spanish': 'Spanisch',
    'language.italian': 'Italienisch',
    'language.german': 'Deutsch',
    'language.portuguese': 'Portugiesisch',

    // Discovery page
    'discovery.exploreMap': 'Karte erkunden',
    'discovery.joinFindMyDJ': 'Tritt FindMyDJ bei',
    'discovery.signUpFree': 'Kostenlos anmelden',
    'discovery.alreadyAccount': 'Bereits ein Konto?',
    'discovery.signIn': 'Anmelden',

    // Forum
    'forum.title': 'Community-Forum',
    'forum.subtitle': 'Teile deine Fragen, Tipps und Erfahrungen mit der DJ-Community',
    'forum.createPost': 'Neuer Beitrag',
    'forum.searchForum': 'Im Forum suchen...',
    'forum.backToForum': 'Zurück zum Forum',
    'forum.all': 'Alle',
    'forum.questions': 'Fragen',
    'forum.tips': 'Tipps',
    'forum.discussions': 'Diskussionen',
    'forum.equipment': 'Ausrüstung',
    'forum.gigs': 'Auftritte',
    'forum.music': 'Musik',
    'forum.events': 'Veranstaltungen',
    'forum.newest': 'Neueste',
    'forum.popular': 'Beliebteste',
    'forum.mostReplies': 'Meiste Antworten',
    'forum.noPostsFound': 'Keine Beiträge gefunden',
    'forum.startDiscussion': 'Starte eine neue Diskussion!',
    'forum.timeAgo.lessThanHour': 'Vor weniger als einer Stunde',
    'forum.timeAgo.hours': 'Vor {hours}h',
    'forum.timeAgo.days': 'Vor {days}T',

    // Messages
    'messages.title': 'Nachrichten',
    'messages.noPermission': 'Sie haben keine Berechtigung, auf Nachrichten zu antworten',
    'messages.searchConversations': 'Unterhaltungen suchen...',
    'messages.noConversations': 'Noch keine Unterhaltungen',
    'messages.startMessaging': 'Beginnen Sie mit anderen DJs und Veranstaltern zu chatten!',
    'messages.typeMessage': 'Nachricht eingeben...',
    'messages.selectConversation': 'Unterhaltung auswählen',
    'messages.chooseConversation': 'Wählen Sie eine Unterhaltung aus der Liste, um zu chatten',
    'messages.online': 'Online',
    'messages.offline': 'Offline',
    'messages.client': 'Kunde',

    // Formulare und Platzhalter
    'forms.yourName': 'Ihr Name',
    'forms.fanMelomane': 'Fan / Musikliebhaber',
    'forms.ruleName': 'Regelname',
    'forms.price': 'Preis',
    'forms.newPlaylist': 'Meine neue Playlist',
    'forms.addTag': 'Tag hinzufügen',

    // Benachrichtigungen und Systemnachrichten
    'notifications.infoCopied': 'Informationen in die Zwischenablage kopiert!',
    'notifications.linkCopied': 'Link in die Zwischenablage kopiert!',
    'notifications.subscriptionCancelled': 'Abonnement erfolgreich gekündigt! (Simulation)',
    'notifications.pricesSaved': 'Preise erfolgreich gespeichert!',
    'notifications.paymentError': 'Fehler beim Zahlungsvorgang. Bitte versuchen Sie es erneut.',
    'notifications.cancellationError': 'Fehler bei der Stornierung. Bitte versuchen Sie es erneut.',
    'notifications.planChangeError': 'Fehler beim Planwechsel. Bitte versuchen Sie es erneut.',
    'notifications.loginRequired': 'Bitte melden Sie sich an, um Musik zu kaufen',
    'notifications.trackAlreadyOwned': 'Sie besitzen diesen Track bereits',
    'notifications.purchaseError': 'Fehler beim Kauf. Bitte versuchen Sie es erneut.',
    'notifications.downloadStarted': 'Download läuft...',
    'notifications.bookingRequestSent': 'Buchungsanfrage gesendet! Der DJ wird Sie bald kontaktieren.',

    // Preisgestaltung
    'pricing.title': 'Preisgestaltung',
    'pricing.saveAll': 'Alles Speichern',
    'pricing.priceRules': 'Preisregeln',
    'pricing.newRule': 'Neue Regel',
    'pricing.ruleName': 'Regelname',
    'pricing.price': 'Preis',
    'pricing.add': 'Hinzufügen',
    'pricing.cancel': 'Abbrechen',
    'pricing.descriptionOptional': 'Beschreibung (optional)',
    'pricing.musicPricing': 'Musikpreise',
    'pricing.currentPrice': 'Aktueller Preis',
    'pricing.customPrice': 'Benutzerdefinierter Preis',
    'pricing.customPricePlaceholder': 'Benutzerdefinierter Preis',
    'pricing.averagePrice': 'Durchschnittspreis',
    'pricing.estimatedRevenue': 'Geschätzte Einnahmen',
    'pricing.afterCommission': 'Nach 2% Provision',
    'pricing.configuredMusic': 'Konfigurierte Musik',
    'pricing.singleStandard': 'Single Standard',
    'pricing.remixPremium': 'Remix Premium',
    'pricing.singleStandardDesc': 'Standardpreis für eine Single',
    'pricing.remixPremiumDesc': 'Preis für exklusive Remixe',
    'pricing.single': 'Single',
    'pricing.album': 'Album',
    'pricing.remix': 'Remix',
    'pricing.exclusive': 'Exklusiv',

    // Playlist
    'playlist.title': 'Playlists filtern und sortieren',
    'playlist.create': 'Erstellen',
    'playlist.createPlaylist': 'Playlist erstellen',
    'playlist.playlistName': 'Playlist-Name *',
    'playlist.playlistNamePlaceholder': 'Playlist-Name',
    'playlist.description': 'Beschreibung',
    'playlist.descriptionPlaceholder': 'Playlist-Beschreibung',
    'playlist.tags': 'Tags',
    'playlist.addTag': 'Tag hinzufügen',
    'playlist.addTagPlaceholder': 'Tag hinzufügen',
    'playlist.publicPlaylist': 'Öffentliche Playlist',
    'playlist.collaborativePlaylist': 'Kollaborative Playlist',
    'playlist.searchPlaylists': 'Playlists suchen...',
    'playlist.all': 'Alle',
    'playlist.personal': 'Persönlich',
    'playlist.shared': 'Geteilt',
    'playlist.public': 'Öffentlich',
    'playlist.favorites': 'Favoriten',
    'playlist.recentlyModified': 'Kürzlich geändert',
    'playlist.recentlyCreated': 'Kürzlich erstellt',
    'playlist.name': 'Name',
    'playlist.duration': 'Dauer',
    'playlist.trackCount': 'Anzahl Tracks',
    'playlist.tracks': 'Tracks',
    'playlist.noPlaylistsFound': 'Keine Playlists gefunden',
    'playlist.noPlaylists': 'Keine Playlists',
    'playlist.modifySearch': 'Versuchen Sie, Ihre Suche zu ändern',
    'playlist.createFirst': 'Erstellen Sie Ihre erste Playlist, um zu beginnen',
    'playlist.createFirstButton': 'Meine erste Playlist erstellen',

    // Filtri e ordinamento
    'filters.newest': 'Neueste',
    'filters.priority': 'Priorität',
    'filters.bestRated': 'Am besten bewertet',
    'filters.automatic': 'Automatisch',
    'filters.highQuality': 'Hoch (320 kbps)',
    'filters.relaxation': 'Entspannung',
    'filters.sport': 'Sport',
    'filters.allPrices': 'Alle Preise',
    'filters.under2euros': 'Unter 2€'
  },
  pt: {
    // Navigation
    'nav.discovery': 'Descoberta',
    'nav.artists': 'Artistas',
    'nav.events': 'Eventos',
    'nav.dashboard': 'Painel',
    'nav.forum': 'Fórum',
    'nav.messages': 'Mensagens',
    'nav.musicStore': 'Loja de Música',
    'nav.musicHub': 'Music Hub',
    'nav.subscription': 'Subscrição',
     'nav.logout': 'Terminar Sessão',
     'nav.createAccount': 'Criar Conta',
    
    // General
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.book': 'Reservar',
    'common.contact': 'Contactar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.download': 'Descarregar',
    'common.upload': 'Carregar',
    'common.bookings': 'reservas',
    
    // DJ Map
    'map.title': 'Mapa de DJs',
    'map.searchCity': 'Pesquisar uma cidade...',
    'map.allStyles': 'Todos os estilos',
    'map.allAvailability': 'Toda disponibilidade',
    'map.availableNow': 'Disponível agora',
    'map.thisWeekend': 'Este fim de semana',
    
    // DJ Profile
    'profile.about': 'Sobre',
    'profile.music': 'Música',
    'profile.events': 'Eventos',
    'profile.booking': 'Reserva',
    'profile.presskit': 'Kit de Imprensa',
    'profile.bio': 'Biografia',
    'profile.genres': 'Géneros Musicais',
    'profile.location': 'Localização',
    'profile.experience': 'Experiência',
    
    // Press Kit
    'presskit.title': 'Kit de Imprensa',
    'presskit.upload': 'Arraste e solte os seus ficheiros aqui ou clique para selecionar',
    'presskit.supported': 'Formatos suportados: PDF, JPG, PNG, MP3, MP4',
    'presskit.documents': 'Documentos',
    'presskit.no_documents': 'Nenhum documento disponível',
    
    // Booking
    'booking.title': 'Reservar este artista',
    'booking.date': 'Data do evento',
    'booking.time': 'Hora',
    'booking.duration': 'Duração',
    'booking.venue': 'Local',
    'booking.budget': 'Orçamento',
    'booking.message': 'Mensagem',
    'booking.submit': 'Enviar pedido',
    
    // Language selector
    'language.select': 'Selecionar idioma',
    'language.french': 'Francês',
    'language.english': 'Inglês',
    'language.spanish': 'Espanhol',
    'language.italian': 'Italiano',
    'language.german': 'Alemão',
    'language.portuguese': 'Português',

    // Discovery page
    'discovery.exploreMap': 'Explorar o mapa',
    'discovery.joinFindMyDJ': 'Junte-se ao FindMyDJ',
    'discovery.signUpFree': 'Registar gratuitamente',
    'discovery.alreadyAccount': 'Já tem uma conta?',
    'discovery.signIn': 'Iniciar sessão',

    // Forum
    'forum.title': 'Fórum da Comunidade',
    'forum.subtitle': 'Partilhe as suas perguntas, dicas e experiências com a comunidade DJ',
    'forum.createPost': 'Nova publicação',
    'forum.searchForum': 'Pesquisar no fórum...',
    'forum.backToForum': 'Voltar ao fórum',
    'forum.all': 'Todos',
    'forum.questions': 'Perguntas',
    'forum.tips': 'Dicas',
    'forum.discussions': 'Discussões',
    'forum.equipment': 'Equipamento',
    'forum.gigs': 'Concertos',
    'forum.music': 'Música',
    'forum.events': 'Eventos',
    'forum.newest': 'Mais recentes',
    'forum.popular': 'Mais populares',
    'forum.mostReplies': 'Mais respostas',
    'forum.noPostsFound': 'Nenhuma publicação encontrada',
    'forum.startDiscussion': 'Comece uma nova discussão!',
    'forum.timeAgo.lessThanHour': 'Há menos de uma hora',
    'forum.timeAgo.hours': 'Há {hours}h',
    'forum.timeAgo.days': 'Há {days}d',

    // Messages
    'messages.title': 'Mensagens',
    'messages.noPermission': 'Não tem permissão para responder a mensagens',
    'messages.searchConversations': 'Pesquisar conversas...',
    'messages.noConversations': 'Ainda não há conversas',
    'messages.startMessaging': 'Comece a trocar mensagens com outros DJs e organizadores de eventos!',
    'messages.typeMessage': 'Digite uma mensagem...',
    'messages.selectConversation': 'Selecionar uma conversa',
    'messages.chooseConversation': 'Escolha uma conversa da lista para começar a conversar',
    'messages.online': 'Online',
    'messages.offline': 'Offline',
    'messages.client': 'Cliente',

    // Formulários e marcadores de posição
    'forms.yourName': 'O seu nome',
    'forms.fanMelomane': 'Fã / Melómano',
    'forms.ruleName': 'Nome da regra',
    'forms.price': 'Preço',
    'forms.newPlaylist': 'A minha nova playlist',
    'forms.addTag': 'Adicionar tag',

    // Notificações e mensagens do sistema
    'notifications.infoCopied': 'Informações copiadas para a área de transferência!',
    'notifications.linkCopied': 'Link copiado para a área de transferência!',
    'notifications.subscriptionCancelled': 'Subscrição cancelada com sucesso! (Simulação)',
    'notifications.pricesSaved': 'Preços guardados com sucesso!',
    'notifications.paymentError': 'Erro durante o processo de pagamento. Tente novamente.',
    'notifications.cancellationError': 'Erro durante o cancelamento. Tente novamente.',
    'notifications.planChangeError': 'Erro durante a mudança de plano. Tente novamente.',
    'notifications.loginRequired': 'Faça login para comprar música',
    'notifications.trackAlreadyOwned': 'Já possui esta faixa',
    'notifications.purchaseError': 'Erro durante a compra. Tente novamente.',
    'notifications.downloadStarted': 'Download em progresso...',
    'notifications.bookingRequestSent': 'Pedido de reserva enviado! O DJ entrará em contacto em breve.',

    // Preços
    'pricing.title': 'Gestão de Preços',
    'pricing.saveAll': 'Guardar Tudo',
    'pricing.priceRules': 'Regras de Preços',
    'pricing.newRule': 'Nova Regra',
    'pricing.ruleName': 'Nome da regra',
    'pricing.price': 'Preço',
    'pricing.add': 'Adicionar',
    'pricing.cancel': 'Cancelar',
    'pricing.descriptionOptional': 'Descrição (opcional)',
    'pricing.musicPricing': 'Preços por Música',
    'pricing.currentPrice': 'Preço atual',
    'pricing.customPrice': 'Preço personalizado',
    'pricing.customPricePlaceholder': 'Preço personalizado',
    'pricing.averagePrice': 'Preço Médio',
    'pricing.estimatedRevenue': 'Receitas Estimadas',
    'pricing.afterCommission': 'Após comissão de 2%',
    'pricing.configuredMusic': 'Músicas Configuradas',
    'pricing.singleStandard': 'Single Standard',
    'pricing.remixPremium': 'Remix Premium',
    'pricing.singleStandardDesc': 'Preço padrão para um single',
    'pricing.remixPremiumDesc': 'Preço para remixes exclusivos',
    'pricing.single': 'Single',
    'pricing.album': 'Álbum',
    'pricing.remix': 'Remix',
    'pricing.exclusive': 'Exclusivo',

    // Playlist
    'playlist.title': 'Filtrar e ordenar as playlists',
    'playlist.create': 'Criar',
    'playlist.createPlaylist': 'Criar uma playlist',
    'playlist.playlistName': 'Nome da playlist *',
    'playlist.playlistNamePlaceholder': 'Nome da playlist',
    'playlist.description': 'Descrição',
    'playlist.descriptionPlaceholder': 'Descrição da playlist',
    'playlist.tags': 'Tags',
    'playlist.addTag': 'Adicionar tag',
    'playlist.addTagPlaceholder': 'Adicionar uma tag',
    'playlist.publicPlaylist': 'Playlist pública',
    'playlist.collaborativePlaylist': 'Playlist colaborativa',
    'playlist.searchPlaylists': 'Pesquisar playlists...',
    'playlist.all': 'Todas',
    'playlist.personal': 'Pessoais',
    'playlist.shared': 'Partilhadas',
    'playlist.public': 'Públicas',
    'playlist.favorites': 'Favoritos',
    'playlist.recentlyModified': 'Recentemente modificadas',
    'playlist.recentlyCreated': 'Recentemente criadas',
    'playlist.name': 'Nome',
    'playlist.duration': 'Duração',
    'playlist.trackCount': 'Número de faixas',
    'playlist.tracks': 'faixas',
    'playlist.noPlaylistsFound': 'Nenhuma playlist encontrada',
    'playlist.noPlaylists': 'Nenhuma playlist',
    'playlist.modifySearch': 'Tente modificar a sua pesquisa',
    'playlist.createFirst': 'Crie a sua primeira playlist para começar',
    'playlist.createFirstButton': 'Criar a minha primeira playlist',

    // Filtros e ordenação
    'filters.newest': 'Mais recentes',
    'filters.priority': 'Prioridade',
    'filters.bestRated': 'Melhor avaliados',
    'filters.automatic': 'Automático',
    'filters.highQuality': 'Alta (320 kbps)',
    'filters.relaxation': 'Relaxamento',
    'filters.sport': 'Desporto',
    'filters.allPrices': 'Todos os preços',
    'filters.under2euros': 'Menos de 2€'
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Récupérer la langue sauvegardée ou utiliser le français par défaut
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'fr';
  });

  useEffect(() => {
    // Sauvegarder la langue sélectionnée
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};